fruits/urls.py
from django.urls import path
from rest_framework.generics import ListCreateAPIView, UpdateAPIView

from .models import Fruit
from .serializer import FruitSerializer
from .views import index, detail_fruit, delete_fruit, create_fruit, update_fuit, liste_fruit, ListeFruitApi, \
    FruitViewSet

app_name = 'fruits_app'


urlpatterns = [
    path('', index, name='home_page'),
    path('fruit/creation', create_fruit, name='create_fruit'),
    path('fruit/modification/<int:pk>', update_fuit, name='modification_fruit'),
    path('fruit/detail/<int:pk>', detail_fruit, name='detail_fruit'),
    path('fruit/suppresion/<int:pk>', delete_fruit, name='supprimer_fruit'),
    path('fruit/liste', liste_fruit, name='list_fruit'),

    # api
    path('api/fruit/liste', ListCreateAPIView.as_view(queryset=Fruit.objects.all(), serializer_class=FruitSerializer), name='ListeFruitApi'),
    path('api/fruit/update/<int:pk>', UpdateAPIView.as_view(queryset=Fruit.objects.all(), serializer_class=FruitSerializer), name='Update'),
    path('api/viewset',  FruitViewSet.as_view({'get': 'list', 'post': 'update'}, name='Viewset configuration')),

]

fruitty/urls.py
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import include, path

from fruitty import settings

urlpatterns = [
    #    path('admin/', admin.site.urls),
    path('', include('fruits.urls', namespace='fruits_app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fruits/models.py
from django.db import models


class Fruit(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nom du fruit')
    description = models.TextField(verbose_name='Description du fruit', blank=True, null=True)
    image = models.ImageField(verbose_name='Image du fruit', blank=True, null=True, upload_to='media/fruits')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name.upper()

fruits/forms.py
from django import forms
from django.forms import widgets

from fruits.models import Fruit


class CreateFruit(forms.ModelForm):
    class Meta:
        model = Fruit
        fields = ['name', 'description', 'image']

fruits/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.template.defaulttags import csrf_token
from rest_framework import viewsets, renderers
from rest_framework.decorators import action
from rest_framework.response import Response
from fruits.forms import CreateFruit
from fruits.models import Fruit
from fruits.serializer import FruitSerializer


def index(request):

    all_fruit = Fruit.objects.all()[:5] # juste 5 fruits

    return render(request, 'base.html', {'all_fruit': all_fruit})

def detail_fruit(request, pk):

    try :
        fruit = Fruit.objects.get(pk=pk)
    except :
        messages.error(request, f"le fruit avec l'identifiant {pk}")
        return redirect("fruits_app:home_page")

    return render(request, 'detail_fruit.html', context={'fruit': fruit})

def delete_fruit(request, pk):

    name_fuit = ""

    try :
        fruit = Fruit.objects.get(pk=pk)
        name_fuit = fruit.name
        fruit.delete()

    except :
        messages.error(request, f"Une erreur est survenue")
        return redirect("fruits_app:home_page")

    messages.info(request, f"le fruit : {name_fuit} a ete supprimer avec success")
    return redirect("fruits_app:home_page")


def create_fruit(request):
    """
    Vue de creation d'un fruit,
    """

    # on charge le formulaire
    form = CreateFruit()

    if request.method == "POST":
        form = CreateFruit(request.POST, request.FILES)
        if form.is_valid():
            try:
                fruit = form.save(commit=True)
                fruit.save()
            except Exception as e:
                messages.error(request, f"Impossible d'enregistre le fruit{e}")
            return redirect('fruits_app:detail_fruit', fruit.pk)

        else:
            context = {
                "form": form,
                'error' : form.errors,
            }
            return render(request, 'create_fruit.html', context)

    # contexte a injecter dans le template
    context = {
        'form': form,
    }
    return render(request, 'create_fruit.html', context)

def update_fuit(request, pk):
    """
        Vue de mise a jour d'un fruit existant
    """
    # on va s'assurer que le fruit existe
    try:
        fruit = Fruit.objects.get(pk=pk)

    except :
        messages.error(request, f"le fruit avec l'identifiant {pk}")
        return redirect("fruits_app:home_page") # si le fruit n'existe pas on retourne a la page d'accueil

    # on passe l'instance de fruit dans le formulaire (les valeurs de ses champ dans la base de donnne )
    form = CreateFruit(instance=fruit)
    if request.method == "POST":
        form = CreateFruit(request.POST, request.FILES)
        if form.is_valid():
            # on s'assure que l'enregistrement se passe bien
            try:
                fruit.name = form.cleaned_data['name']
                fruit.description = form.cleaned_data['description']
                fruit.image = form.cleaned_data['image']
                fruit.save()
                redirect('fruits_app:detail_fruit', fruit.pk)
            except Exception as e:
                messages.error(request, f"Impossible d'enregistre le fruit{e}")
            return redirect('fruits_app:detail_fruit', fruit.pk)

        else:
            context = {
                "form": form,
                'error': form.errors,
            }
            return render(request, 'create_fruit.html', context)

    context = {
        'form': form,
    }
    return render(request, 'create_fruit.html', context)


def liste_fruit(request):

    all_fruit = Fruit.objects.all()

    return render(request, 'liste_fruit.html', {'all_fruit': all_fruit})


class ListeFruitApi(viewsets.ModelViewSet):
    queryset = Fruit.objects.all()
    serializer_class = FruitSerializer()


class FruitViewSet(viewsets.ModelViewSet):

    queryset = Fruit.objects.all()
    serializer_class = FruitSerializer


    @action(detail=True, renderer_classes=[renderers.StaticHTMLRenderer])
    def highlight(self, request, *args, **kwargs):
        fruit = self.get_object()
        return Response(fruit.highlighted)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titre %} Bienvenue sur Fruitty {% endblock titre %}</title>
    <!-- integration de bootstrap 5 -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>
<body>
    <header>
        <h2>Petite navigation</h2>
        <nav class="navbar">
            <div class="container-fluid ">
               <ul class="navbar-nav">
                   <li class="nav-item"><a href="{% url 'fruits_app:create_fruit' %}">Creer un nouveau fruit</a></li>
                   <li class="nav-item"><a href="{% url 'fruits_app:list_fruit' %}">Lister tout le fruit</a></li>
               </ul>
            </div>
        </nav>
    </header>


    <div class="container mt-3">
        <h3 > liste de fruit</h3>
        {% block content %}
            {% if all_fruit %}

                {% for f in all_fruit %}
                <li>
                    <a href="{% url 'fruits_app:detail_fruit'  f.pk %}">{{ f.name }}</a>
                </li>
                {% endfor %}
            {% endif %}
        {% endblock content %}
    </div>



    {% block java_script %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js" integrity="sha384-7qAoOXltbVP82dhxHAUje59V5r2YsVfBafyUDxEdApLPmcdhBPg1DKg1ERo0BZlK" crossorigin="anonymous"></script>
    {% endblock java_script %}
</body>
</html>

templates/create_fruit.html
{% extends 'base.html' %}



{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_div }}

        <input type="submit" value="Enregistrer">

    </form>

{% endblock content %}

templates/detail_fruit.html
{% extends 'base.html' %}


{% block content %}

    <div>
        {% if fruit.image %} <li><img src="{{ fruit.image.url }}" alt=""></li> {% endif %}
        <h1>{{ fruit.name }}</h1>
        <p>{{ fruit.description }}</p>
        <a href="{% url 'fruits_app:modification_fruit' fruit.pk %}">Modifier</a>
        <a href="{% url 'fruits_app:supprimer_fruit' fruit.pk %}">Supprimer</a>
    </div>

{% endblock %}

templates/liste_fruit.html
{% extends 'base.html' %}


{% block content %}
    {% if all_fruit %}

        {% for f in all_fruit %}
        <li>
            <a href="{% url 'fruits_app:detail_fruit'  f.pk %}">{{ f.name }}</a>
        </li>
        {% endfor %}
    {% endif %}
{% endblock content %}